# Generated by Django 4.0.5 on 2022-07-06 23:17

import cadastros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='cep',
            field=models.CharField(blank=True, max_length=9, validators=[cadastros.models.validar_cep], verbose_name='CEP'),
        ),
    ]
