# Generated by Django 4.0.5 on 2022-07-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenciaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('dia', models.DateField(auto_now_add=True, verbose_name='Data do registro')),
                ('entrada', models.TimeField(blank=True, null=True, verbose_name='Entrada')),
                ('saida', models.TimeField(blank=True, null=True, verbose_name='Saída')),
            ],
            options={
                'verbose_name': 'Frequência do Aluno',
                'verbose_name_plural': 'Frequências dos Alunos',
            },
        ),
    ]
