# Generated by Django 4.0.5 on 2022-07-06 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frequencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequenciaaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
